/**
 * Account_Junior extends Account
 * @see Account
 *
 * @author Xi Xia
 * @version 1.1
 */
public class Account_Junior extends Account {

    /**
     * Open a junior account
     * @param birth use the birthday as default PIN
     * @return accID
     * @see Account#writeAccFinder(java.lang.String, java.lang.String, java.lang.String, int)
     * @see Account#writeAcc()
     */

    public int openJuniorAccount(String birth){
        /**
         * Use the customer's birthday as default PIN when an account is opened
         * AccID is generated by openAccount() function in Account class, and it's unique
         @see: Account#openAccount(java.lang.String)
         */
        openAccount(birth);
        setType(Type.JUNIOR);
        System.out.println(toString());
        return this.accID; //to be recorded in File "CreditAgency.txt"
    }
}
