/**
 * Account_Current extends Account
 * @see Account
 *
 * @author Xi Xia
 * @version 1.1
 */
public class Account_Current extends Account {

    /**
     * Open a current account
     * @param birth use the birthday as default PIN
     * @return accID
     * @see Account#writeAccFinder(java.lang.String, java.lang.String, java.lang.String, int)
     * @see Account#writeAcc()
     */
    public int openCurrentAccount(String birth){
        /**
         * Only current accounts allow withdrawal resulting in a negative balance.
         * (no more than the overdraft limit permits)
         *
         * Use the customer's birthday as default PIN when an account is opened
         * AccID is generated by openAccount() function in Account class, and it's unique
         @see: Account#openAccount(java.lang.String)
         */
        openAccount(birth);
        setType(Type.CURRENT);
        this.setOverdraftLimit(2000);
        System.out.println(toString());
        return this.accID; //to be recorded in File "CreditAgency.txt"
    }

}
