public class Account_Junior extends Account {

    /**
     * open a junior account
     * @param birth
     * @return
     */

    public int openJuniorAccount(String birth){
        /**
         * Use the customer's birthday as default PIN when an account is opened
         * AccID is generated by openAccount() function in Account class, and it's unique
         @see: Account#openAccount(java.lang.String)
         */
        openAccount(birth);
        setType(Type.JUNIOR);
        System.out.println(toString());
        return this.accID; //to be recorded in File "CreditAgency.txt"
    }
}
